### ISSUE TITLE
Gen folder

### ISSUE THREAD

**Issue by maatthc** [gvalkov/tailon-legacy#10]
Hi, 
I've made some changes to the file "assets/main.js" but when I install the package, the file "gen/main.js" is not generated from "assets/main.js". Is there any step missing when building the package?

Regards,
MaaT

**Comment by gvalkov** [comment]
Hello @maatthc,

Tailon has a somewhat weird asset pipeline. Front-end dependencies are fetched with `bower` and processed (compiled, minified, concatenated) with [webassets](http://webassets.readthedocs.org/). The driver for this is `tasks.py` and the [invoke](http://invoke.readthedocs.org/en/latest/) tool.

Basically, if you've made a change to `main.js`, you need to run `inv webassets --replace` or `inv webassets --replace --debug` if you don't want to concatenate and minify - try running it both ways and compare the contents of `tailon/templates/index.html` around the `WEBASSETS_{JS,CSS}` placeholders.

I admit that this is poorly documented and not very obvious - let me know if I can assist in any other way.

Best regards,
Georgi

**Comment by maatthc** [comment]
Hi Georgi,
Thanks for the explanation - it makes much sense now.

Cheers
