### ISSUE TITLE
Web GUI does not tail (stick to bottom of log)

### ISSUE THREAD

**Issue by jdrews** [gvalkov/tailon-legacy#13]
The current GUI does not stick to the bottom of the page when new content is added from the log files. The scroll bar starts going up. This is in the latest Chrome release. 

Functionality should be as follows:
1. If user is scrolled to bottom of page, user should stay at bottom while new content is added in
2. If user scrolls up in window, do not tie user to bottom of page, until the scroll to the bottom again. 

A button to jump to bottom and continue tailing would be useful. Perhaps a hover over that only pops up in a corner when user is not tailing bottom of page.

**Comment by gvalkov** [comment]
Thanks for the catch. This is definitely a regression. I'll look into it asap.

**Comment by jdrews** [comment]
Just to make sure it wasn't isolated to Chrome, I have tried it in the latest Firefox (v41) and Internet Explorer 11. All would not stay at the bottom of screen while tailing.

**Comment by jdrews** [comment]
Tested your changes at 887df5f1d4e22ade9efa37dc9cc23a2a62a64aa8 and can confirm it functions properly now in Chrome, Firefox, and IE11. Closing issue. 

As an interesting test, I'll let it continue to tail on all three browsers overnight. If you don't hear from me it went fine.

**Comment by gvalkov** [comment]
Thanks for trying it out. I just put 0.4.2 on PyPi with this fix. Although not perfect, the new scroll handling should be more robust.
