### ISSUE TITLE
Feature Request: Wrap text option

### ISSUE THREAD

**Issue by jdrews** [gvalkov/tailon-legacy#15]
Requesting new feature to be able to wrap text inside window. The reasoning behind this is to make sure all text is readable as it scrolls by. 

It would be nice if this was a configuration in the yaml config file and in the wrench gear icon dropdown. If I had to choose between wrench gear and yaml config file I would choose yaml config file.

**Comment by gvalkov** [comment]
Definitely. I'll look into it when I get time to work on tailon.

**Comment by solher** [comment]
+1 for the wrap text option. That would be really cool.

**Comment by pzxbc** [comment]
+1. now i add this to log-view .log-entry in main.css for text wrap

``` css
word-wrap: break-word;
word-break: normal;
```

**Comment by gvalkov** [comment]
Implemented in 70bca8041c1522dd571ea04d67f2cbe0a0a41c05. Please close the issue if you find that it works well enough for you. Thanks.

**Comment by jdrews** [comment]
The wrap text checkbox works in Chrome 46, Firefox 42, and IE 11. 

Is there a way to set this from the config file passed in on start?

**Comment by chines** [comment]
Thanks again for this.
