### ISSUE TITLE
In version v5.X, the bottom of tailon is not displayed

### ISSUE THREAD

**Issue by CloudSurgeon** [gvalkov/tailon-legacy#25]
Last few lines are truncated from display, including the scroll bars. Appears in multiple browsers (IE, FF, and Chrome) and on Win and Mac. Verified issue is not present in 0.4.2

0.4.2
![image](https://cloud.githubusercontent.com/assets/12521930/14084418/a20e783a-f4e8-11e5-9aa0-6643c6924b40.png)

0.5.0/0.5.1
![image](https://cloud.githubusercontent.com/assets/12521930/14084429/ac81090e-f4e8-11e5-8310-06c322a807ac.png)

**Comment by gvalkov** [comment]
Thanks, that's a good catch and a nasty regression. I'm in the process of refactoring tailon and once I'm done, I'll make sure to fix this.

**Comment by gvalkov** [comment]
This should have been fixed in tailon 0.6.0. Please re-open this issue if the problem persists. Thanks for the report.
