### ISSUE TITLE
The empty lines are not being showed

### ISSUE THREAD

**Issue by tolinwei** [gvalkov/tailon-legacy#28]
I tried this project, it's great, except issue #25 
and the other thing is:

The empty lines in the file it not being printed out in the front-end UI.

Do I need extra setting or this is the nature of this project?
Thanks,
-Wei

**Comment by gvalkov** [comment]
Hi, @tolinwei. This issue along with many others have been fixed in the develop branch, but I just haven't had the time to cut out a proper release. I'll do my best to have it soon.

**Comment by tolinwei** [comment]
Thanks @gvalkov, this issue should be ok to close, look forward to your new update soon.
-Wei
