### ISSUE TITLE
Scrollback does not work

### ISSUE THREAD

**Issue by m-ruhl** [gvalkov/tailon-legacy#29]
Hey,

I just installed tailon on my PI. Exactly what I needed 😄 

I guess when you scroll to the top, older lines should be fetched?
But nothing happens.

Another thing, would be great if you can configure "tail-lines" 😉 

Cheers
-Michael

**Comment by gvalkov** [comment]
Hello Michael,

The number of lines to tail should be configurable. There is a "Tail lines" input field in the configuration popup (wrench icon in the top-right). It's basically the value passed to `tail -n`. It's probably a good idea to make the initial value configurable from the cli/config file as well.

As for the scrolling issue, well ... it should work :) Scrolling to the very bottom should switch to follow mode (i.e. `tail -f`), while scrolling up should show you what was already tailed (for up to "Scrollback lines" number of lines).

Kind regards,
Georgi
