### ISSUE TITLE
file list sort order by date, not by name

### ISSUE THREAD

**Issue by sgohl** [gvalkov/tailon-legacy#43]
I generate log files from a script with timestamp in it.

tailon will output the list of files in name-sorted order. But then, the oldest is shown first and the newest is at the very bottom.

Also I want to hide the folder location of the log files, since the line wraps because of the path-length.

Any chance to adjust this behaviour? I couldn't find the relevant place in the code :-(

**Comment by gvalkov** [comment]
These sound like useful features - I'll consider them for next version. 

At the moment, you can make the paths shorter by changing the working directory of tailon when you run it. For example: 

```bash
tailon -f /very/long/path  # from
cd /very/long/path && tailon -f .  # to
```

**Comment by sgohl** [comment]
I just found out that the sorting is only old-to-new, when the filename ends with ".log"
If I just use filenames like "13.06.2017-21:00" I have the newest on top. 
regarding the path, I'll try your suggestion, that would be sufficient for me. 

thanks a lot!
