### ISSUE TITLE
extra-files-dir required directory on stable, fixed on dev

### ISSUE THREAD

**Issue by camjac251** [gvalkov/tailon-legacy#56]
With the latest stable release on pypi, I get `FileNotFoundError: [Errno 2] No such file or directory: '/etc/tailon/files.d/`

I think this is fixed on the development branch. Could it be pushed to stable?

**Comment by camjac251** [comment]
I used pipsi so I'm unable to use the dev branch.

**Comment by gvalkov** [comment]
This should have been fixed by #55. Sorry for the inconvenience.
