### ISSUE TITLE
awk: not an option --sandbox

### ISSUE THREAD

**Issue by ghost** [gvalkov/tailon-legacy#62]
When I try to do something as simple as `{ print $1 }`, I get an error,: `awk: not an option: --sandbox. It seems the version of awk I am running doesn't have the `sandbox` argument. Does anyone know which version of awk this requires? I have whatever Ubuntu 14.04 ships with. Apparently that is mawk 1.3.3.

**Comment by chines** [comment]
v4.0 of gawk (default awk in centos/rhel) introduced --sandbox:

https://www.gnu.org/software/gawk/manual/html_node/Feature-History.html

**Comment by ghost** [comment]
Thank you. `sudo apt-get install gawk && sudo apt-get remove mawk` took care of the error.

**Comment by GabrielBB** [comment]
It's 2022 and I don't know what is this package for but it was a dependency to some script I was running, @sophieforceno 's command solved the problem
