### ISSUE TITLE
LICENCE same as new tailon?

### ISSUE THREAD

**Issue by Chris2048** [gvalkov/tailon-legacy#63]
Hi, The new tailon has an Apache licence, does legacy tailon have a similar license?
I'd like to fork the python-based version so I can continue to use in a python ecosystem, but afaik its is not permitted to do so?

**Comment by gvalkov** [comment]
Hi Chris. The Python tailon is licensed under the 3-clause BSD license. You're welcome to do anything you want with it (just need to keep the first line of the LICENSE file).
